log.filename: ./http_requests.log
db.filename: ./imdb

# logging
logbook:
  include:
    - /api/**
  filter:
    enabled: true
  secure-filter.enabled: true
  format:
    style: http
  strategy: body-only-if-status-at-least
  obfuscate:
    headers:
      - Authorization
    write:
      chunk-size: 1000


logging.level:
  root: INFO
  org.zalando.logbook.Logbook: TRACE

spring:
  # database
  datasource:
    url: jdbc:h2:file:${db.filename};MULTI_THREADED=1;PAGE_SIZE=8192
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

  batch:
    job:
      enabled: false
